### PR TITLE
Fixed too many legendaries

### LINKED ISSUE #73: Too many legendaries and inconsistent amount of legendaries

### PR DESCRIPTION
**Pull request by SimonBaars**
The amount of legendaries previously depended on the size of the pack. Now I made it that once every 500 pokemon a legendary will show up.

Closes #73

### CODE REVIEW

**Review by loehnertz — APPROVED** [review]

File: src/main/kotlin/service/store/StoreService.kt [hunk 1]
```diff
@@ -90,10 +90,9 @@ class StoreService {
         val sortedPokemons = pokemons.sortedBy { it.xp }.asReversed()
 
         val possiblePokemons = arrayListOf<ThinPokemon>()
-		if(Random.nextInt(0, LegendaryPokemonInBoosterPack) == 0) possiblePokemons.add(PokeApi().getPokemon(LegendaryPokemon.random()));
         sortedPokemons.forEachIndexed { index, pokemon -> repeat(index + 1) { possiblePokemons.add(pokemon) } }
 
-        val drawnPokemons = possiblePokemons.shuffled().take(BoosterpackSize)
+        val drawnPokemons = possiblePokemons.shuffled().map { pkmn -> if (Random.nextInt(0, LegendaryPokemonInBoosterPack) == 0) PokeApi().getPokemon(LegendaryPokemon.random()) else pkmn }.take(BoosterpackSize)
```
Comment (CJStuart) [inline src/main/kotlin/service/store/StoreService.kt:95]: This line is pretty long

**Review by CJStuart — APPROVED** [review]

File: src/main/kotlin/service/store/StoreService.kt (hunk 1 above)
Comment (SimonBaars) [reply src/main/kotlin/service/store/StoreService.kt:95]: I like it :)
